stages:
  - test

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

test:
  stage: test
  image: registry.gitlab.com/musicscience37/my-cpp-env-docker:clang14
  script:
    - pipx install poetry
    - poetry config virtualenvs.in-project true
    - poetry env use python3.9
    - poetry install
    - poetry run pytest --cov clang_tidy_checker/ tests
    - poetry run coverage report
    - poetry run coverage xml
    - poetry run coverage html
  cache:
    key:
      prefix: poetry-linux
      files:
        - poetry.lock
    paths:
      - .venv
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
