stages:
  - test
  - deploy

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

.poetry-base:
  image: registry.gitlab.com/musicscience37/my-cpp-env-docker:clang14
  before_script:
    - pipx install poetry
    - poetry config virtualenvs.in-project true
    - poetry env use python3.9
    - poetry install
  cache:
    key:
      prefix: poetry-linux
      files:
        - poetry.lock
    paths:
      - .venv

test:
  extends: .poetry-base
  stage: test
  script:
    - poetry run pytest --cov clang_tidy_checker/ tests
    - poetry run coverage report
    - poetry run coverage xml
    - poetry run coverage html
  artifacts:
    paths:
      - .coverage
      - coverage.xml
      - htmlcov
      - tests/approvals
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    when: always
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

pre-commit:
  extends: .poetry-base
  stage: test
  script:
    - poetry run pre-commit run --all-files

static-checks:
  extends: .poetry-base
  stage: test
  script:
    - poetry run pylint clang_tidy_checker tests
    - poetry run mypy clang_tidy_checker tests
    - poetry run flake8 clang_tidy_checker tests

publish-package:
  extends: .poetry-base
  stage: deploy
  script:
    - poetry build
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi/simple
    - poetry config http-basic.gitlab gitlab-ci-token ${CI_JOB_TOKEN}
    - poetry config pypi-token.pypi ${PYPI_TOKEN}
    - poetry publish -r gitlab
    - poetry publish
  only:
    - tags
